# Generated by Django 2.1.7 on 2019-05-30 18:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='名称')),
                ('desc', models.TextField(default='', verbose_name='地区描述')),
                ('category_type', models.IntegerField(choices=[(1, '一级地区'), (2, '二级地区'), (3, '三级地区')], verbose_name='地区级别')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='maps.CityDict', verbose_name='父级类目')),
            ],
            options={
                'verbose_name': '多级地区',
                'verbose_name_plural': '多级地区',
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='监控点名称')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('dev_id', models.CharField(default='', max_length=100, unique=True, verbose_name='设备id')),
                ('resource_id', models.CharField(default='', max_length=100, verbose_name='视频流id')),
                ('status', models.IntegerField(default=1, verbose_name='设备状态')),
                ('address', models.CharField(default='苏州市平江路', max_length=100, verbose_name='地址')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='maps.CityDict', verbose_name='所属地区')),
            ],
            options={
                'verbose_name': '地图管理',
                'verbose_name_plural': '地图管理',
            },
        ),
    ]
