# Generated by Django 2.1.7 on 2019-05-30 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HwHttp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, '请求'), (2, '返回')], verbose_name='方式')),
                ('add_time', models.FloatField(default=1.0, verbose_name='请求时间')),
            ],
            options={
                'verbose_name': '华为统计',
                'verbose_name_plural': '华为统计',
                'ordering': ['-add_time'],
            },
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='操作用户')),
                ('ip_address', models.CharField(default='', max_length=30, verbose_name='ip地址')),
                ('user_type', models.IntegerField(choices=[(1, '增加'), (2, '修改'), (3, '删除'), (4, '登陆'), (5, '退出'), (6, '查看')], verbose_name='操作类型')),
                ('desc', models.CharField(default='', max_length=100, verbose_name='操作详情')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '用户操作日志',
                'verbose_name_plural': '用户操作日志',
                'ordering': ['-add_time'],
            },
        ),
        migrations.CreateModel(
            name='ZwHttp1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, '请求'), (2, '返回')], verbose_name='方式')),
                ('add_time', models.FloatField(default=1.0, verbose_name='请求时间')),
            ],
            options={
                'verbose_name': '中威统计',
                'verbose_name_plural': '中威统计',
                'ordering': ['-add_time'],
            },
        ),
        migrations.CreateModel(
            name='ZwHttp2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, '请求'), (2, '返回')], verbose_name='类别')),
                ('type', models.IntegerField(choices=[(1, '图片'), (2, '视频')], verbose_name='方式')),
                ('add_time', models.FloatField(default=1.0, verbose_name='请求时间')),
            ],
            options={
                'verbose_name': '中威发送统计',
                'verbose_name_plural': '中威发送统计',
                'ordering': ['-add_time'],
            },
        ),
    ]
