# Generated by Django 2.1.7 on 2019-05-30 18:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(default='', max_length=1000, verbose_name='监控直播地址')),
                ('monitor_id', models.CharField(max_length=100, verbose_name='播放直播流id')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('map', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='maps.Map', verbose_name='所属设备')),
            ],
            options={
                'verbose_name': '播放视频管理',
                'verbose_name_plural': '播放视频管理',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(default='', max_length=1000, verbose_name='监控录像地址')),
                ('monitor_id', models.CharField(max_length=100, verbose_name='播放录像id')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('map', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='maps.Map', verbose_name='所属设备')),
            ],
            options={
                'verbose_name': '播放录像管理',
                'verbose_name_plural': '播放录像管理',
            },
        ),
    ]
